import type { AquaCrudConfig } from '@/features/aqua/shared/types/aqua-crud';

const documentStatusOptions = [
  { label: 'aqua.status.draft', value: 0 },
  { label: 'aqua.status.posted', value: 1 },
  { label: 'aqua.status.cancelled', value: 2 },
];

const goodsReceiptItemTypeOptions = [
  { label: 'aqua.goodsReceiptItemType.feed', value: 0 },
  { label: 'aqua.goodsReceiptItemType.fish', value: 1 },
];

export const goodsReceiptsConfig: AquaCrudConfig = {
  key: 'goodsReceipts',
  title: 'aqua.pages.goodsReceipts.title',
  description: 'aqua.pages.goodsReceipts.description',
  endpoint: 'GoodsReceipt',
  postingSlug: 'goods-receipt',
  autoPostOnSave: true,
  listStaleTimeMs: 15000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'receiptNo', label: 'aqua.fields.receiptNo', type: 'text', required: true },
    { key: 'receiptDate', label: 'aqua.fields.receiptDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'supplierId', label: 'aqua.fields.supplierId', type: 'number' },
    { key: 'warehouseId', label: 'aqua.fields.warehouseId', type: 'number' },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'receiptNo', label: 'aqua.fields.receiptNo' },
    { key: 'receiptDate', label: 'aqua.fields.receiptDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const feedingsConfig: AquaCrudConfig = {
  key: 'feedings',
  title: 'aqua.pages.feedings.title',
  description: 'aqua.pages.feedings.description',
  endpoint: 'Feeding',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'feedingNo', label: 'aqua.fields.feedingNo', type: 'text', required: true },
    { key: 'feedingDate', label: 'aqua.fields.feedingDate', type: 'datetime', required: true },
    {
      key: 'feedingSlot',
      label: 'aqua.fields.feedingSlot',
      type: 'select',
      required: true,
      options: [
        { label: 'aqua.feedingSlot.morning', value: 0 },
        { label: 'aqua.feedingSlot.evening', value: 1 },
      ],
    },
    {
      key: 'sourceType',
      label: 'aqua.fields.sourceType',
      type: 'select',
      required: true,
      options: [
        { label: 'aqua.sourceType.manual', value: 0 },
        { label: 'aqua.sourceType.planned', value: 1 },
        { label: 'aqua.sourceType.auto', value: 2 },
      ],
    },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'feedingNo', label: 'aqua.fields.feedingNo' },
    { key: 'feedingDate', label: 'aqua.fields.feedingDate' },
    { key: 'feedingSlot', label: 'aqua.fields.feedingSlot' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { feedingSlot: 0, sourceType: 0, status: 0 },
};

export const mortalitiesConfig: AquaCrudConfig = {
  key: 'mortalities',
  title: 'aqua.pages.mortalities.title',
  description: 'aqua.pages.mortalities.description',
  endpoint: 'Mortality',
  postingSlug: 'mortality',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'mortalityDate', label: 'aqua.fields.mortalityDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'mortalityDate', label: 'aqua.fields.mortalityDate' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const transfersConfig: AquaCrudConfig = {
  key: 'transfers',
  title: 'aqua.pages.transfers.title',
  description: 'aqua.pages.transfers.description',
  endpoint: 'Transfer',
  postingSlug: 'transfer',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const shipmentsConfig: AquaCrudConfig = {
  key: 'shipments',
  title: 'aqua.pages.shipments.title',
  description: 'aqua.pages.shipments.description',
  endpoint: 'Shipment',
  postingSlug: 'shipment',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo', type: 'text', required: true },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo' },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const weighingsConfig: AquaCrudConfig = {
  key: 'weighings',
  title: 'aqua.pages.weighings.title',
  description: 'aqua.pages.weighings.description',
  endpoint: 'Weighing',
  postingSlug: 'weighing',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weighingNo', label: 'aqua.fields.weighingNo', type: 'text', required: true },
    { key: 'weighingDate', label: 'aqua.fields.weighingDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'weighingNo', label: 'aqua.fields.weighingNo' },
    { key: 'weighingDate', label: 'aqua.fields.weighingDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const stockConvertsConfig: AquaCrudConfig = {
  key: 'stockConverts',
  title: 'aqua.pages.stockConverts.title',
  description: 'aqua.pages.stockConverts.description',
  endpoint: 'StockConvert',
  postingSlug: 'stock-convert',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'convertNo', label: 'aqua.fields.convertNo', type: 'text', required: true },
    { key: 'convertDate', label: 'aqua.fields.convertDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'convertNo', label: 'aqua.fields.convertNo' },
    { key: 'convertDate', label: 'aqua.fields.convertDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const dailyWeathersConfig: AquaCrudConfig = {
  key: 'dailyWeathers',
  title: 'aqua.pages.dailyWeathers.title',
  description: 'aqua.pages.dailyWeathers.description',
  endpoint: 'DailyWeather',
  listStaleTimeMs: 30000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate', type: 'date', required: true },
    {
      key: 'weatherTypeId',
      label: 'aqua.fields.weatherTypeId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherType',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    {
      key: 'weatherSeverityId',
      label: 'aqua.fields.weatherSeverityId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherSeverity',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
        dependsOnFieldKey: 'weatherTypeId',
        filterColumn: 'WeatherTypeId',
      },
    },
    { key: 'temperatureC', label: 'aqua.fields.temperatureC', type: 'number' },
    { key: 'windKnot', label: 'aqua.fields.windKnot', type: 'number' },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate' },
    { key: 'weatherTypeName', label: 'aqua.fields.weatherTypeId' },
    { key: 'weatherSeverityName', label: 'aqua.fields.weatherSeverityId' },
  ],
};

export const netOperationsConfig: AquaCrudConfig = {
  key: 'netOperations',
  title: 'aqua.pages.netOperations.title',
  description: 'aqua.pages.netOperations.description',
  endpoint: 'NetOperation',
  postingSlug: 'net-operation',
  autoPostOnSave: true,
  listStaleTimeMs: 15000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'operationTypeId',
      label: 'aqua.fields.operationTypeId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'NetOperationType',
        labelKey: 'name',
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    { key: 'operationNo', label: 'aqua.fields.operationNo', type: 'text', required: true },
    { key: 'operationDate', label: 'aqua.fields.operationDate', type: 'date', required: true },
    { key: 'status', label: 'aqua.fields.status', type: 'select', required: true, options: documentStatusOptions },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'operationNo', label: 'aqua.fields.operationNo' },
    { key: 'operationDate', label: 'aqua.fields.operationDate' },
    { key: 'operationTypeName', label: 'aqua.fields.operationTypeId' },
    { key: 'status', label: 'aqua.fields.status' },
  ],
  defaultValues: { status: 0 },
};

export const goodsReceiptLinesConfig: AquaCrudConfig = {
  key: 'goodsReceiptLines',
  title: 'aqua.pages.goodsReceiptLines.title',
  description: 'aqua.pages.goodsReceiptLines.description',
  endpoint: 'GoodsReceiptLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'goodsReceiptId',
      label: 'aqua.fields.goodsReceiptId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'GoodsReceipt',
        labelKeys: ['receiptNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'itemType', label: 'aqua.fields.itemType', type: 'select', required: true, options: goodsReceiptItemTypeOptions },
    {
      key: 'stockId',
      label: 'aqua.fields.stockId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit', type: 'number' },
    { key: 'gramPerUnit', label: 'aqua.fields.gramPerUnit', type: 'number' },
    { key: 'totalGram', label: 'aqua.fields.totalGram', type: 'number' },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number' },
    { key: 'fishAverageGram', label: 'aqua.fields.fishAverageGram', type: 'number' },
    { key: 'fishTotalGram', label: 'aqua.fields.fishTotalGram', type: 'number' },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
  ],
  columns: [
    { key: 'goodsReceiptId', label: 'aqua.fields.goodsReceiptId' },
    { key: 'itemType', label: 'aqua.fields.itemType' },
    { key: 'stockId', label: 'aqua.fields.stockId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'totalGram', label: 'aqua.fields.totalGram' },
  ],
};

export const goodsReceiptFishDistributionsConfig: AquaCrudConfig = {
  key: 'goodsReceiptFishDistributions',
  title: 'aqua.pages.goodsReceiptFishDistributions.title',
  description: 'aqua.pages.goodsReceiptFishDistributions.description',
  endpoint: 'GoodsReceiptFishDistribution',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'goodsReceiptLineId',
      label: 'aqua.fields.goodsReceiptLineId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'GoodsReceiptLine',
        labelKeys: ['id'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
  ],
  columns: [
    { key: 'goodsReceiptLineId', label: 'aqua.fields.goodsReceiptLineId' },
    { key: 'projectCageId', label: 'aqua.fields.projectCageId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
  ],
};

export const feedingLinesConfig: AquaCrudConfig = {
  key: 'feedingLines',
  title: 'aqua.pages.feedingLines.title',
  description: 'aqua.pages.feedingLines.description',
  endpoint: 'FeedingLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'feedingId',
      label: 'aqua.fields.feedingId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Feeding',
        labelKeys: ['feedingNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'stockId',
      label: 'aqua.fields.stockId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit', type: 'number', required: true },
    { key: 'gramPerUnit', label: 'aqua.fields.gramPerUnit', type: 'number', required: true },
    { key: 'totalGram', label: 'aqua.fields.totalGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'feedingId', label: 'aqua.fields.feedingId' },
    { key: 'stockId', label: 'aqua.fields.stockId' },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit' },
    { key: 'totalGram', label: 'aqua.fields.totalGram' },
  ],
};

export const feedingDistributionsConfig: AquaCrudConfig = {
  key: 'feedingDistributions',
  title: 'aqua.pages.feedingDistributions.title',
  description: 'aqua.pages.feedingDistributions.description',
  endpoint: 'FeedingDistribution',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'feedingLineId',
      label: 'aqua.fields.feedingLineId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FeedingLine',
        labelKeys: ['id'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'feedGram', label: 'aqua.fields.feedGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'feedingLineId', label: 'aqua.fields.feedingLineId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'projectCageId', label: 'aqua.fields.projectCageId' },
    { key: 'feedGram', label: 'aqua.fields.feedGram' },
  ],
};

export const transferLinesConfig: AquaCrudConfig = {
  key: 'transferLines',
  title: 'aqua.pages.transferLines.title',
  description: 'aqua.pages.transferLines.description',
  endpoint: 'TransferLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'transferId',
      label: 'aqua.fields.transferId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Transfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'transferId', label: 'aqua.fields.transferId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram' },
  ],
};

export const shipmentLinesConfig: AquaCrudConfig = {
  key: 'shipmentLines',
  title: 'aqua.pages.shipmentLines.title',
  description: 'aqua.pages.shipmentLines.description',
  endpoint: 'ShipmentLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'shipmentId',
      label: 'aqua.fields.shipmentId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Shipment',
        labelKeys: ['shipmentNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'shipmentId', label: 'aqua.fields.shipmentId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram' },
  ],
};

export const mortalityLinesConfig: AquaCrudConfig = {
  key: 'mortalityLines',
  title: 'aqua.pages.mortalityLines.title',
  description: 'aqua.pages.mortalityLines.description',
  endpoint: 'MortalityLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'mortalityId',
      label: 'aqua.fields.mortalityId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Mortality',
        labelKeys: ['id'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'deadCount', label: 'aqua.fields.deadCount', type: 'number', required: true },
  ],
  columns: [
    { key: 'mortalityId', label: 'aqua.fields.mortalityId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'projectCageId', label: 'aqua.fields.projectCageId' },
    { key: 'deadCount', label: 'aqua.fields.deadCount' },
  ],
};

export const weighingLinesConfig: AquaCrudConfig = {
  key: 'weighingLines',
  title: 'aqua.pages.weighingLines.title',
  description: 'aqua.pages.weighingLines.description',
  endpoint: 'WeighingLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'weighingId',
      label: 'aqua.fields.weighingId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Weighing',
        labelKeys: ['weighingNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'measuredCount', label: 'aqua.fields.measuredCount', type: 'number', required: true },
    { key: 'measuredAverageGram', label: 'aqua.fields.measuredAverageGram', type: 'number', required: true },
    { key: 'measuredBiomassGram', label: 'aqua.fields.measuredBiomassGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'weighingId', label: 'aqua.fields.weighingId' },
    { key: 'fishBatchId', label: 'aqua.fields.fishBatchId' },
    { key: 'measuredCount', label: 'aqua.fields.measuredCount' },
    { key: 'measuredAverageGram', label: 'aqua.fields.measuredAverageGram' },
  ],
};

export const stockConvertLinesConfig: AquaCrudConfig = {
  key: 'stockConvertLines',
  title: 'aqua.pages.stockConvertLines.title',
  description: 'aqua.pages.stockConvertLines.description',
  endpoint: 'StockConvertLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'stockConvertId',
      label: 'aqua.fields.stockConvertId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'StockConvert',
        labelKeys: ['convertNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromFishBatchId',
      label: 'aqua.fields.fromFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'toFishBatchId',
      label: 'aqua.fields.toFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true },
  ],
  columns: [
    { key: 'stockConvertId', label: 'aqua.fields.stockConvertId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram' },
  ],
};

export const netOperationLinesConfig: AquaCrudConfig = {
  key: 'netOperationLines',
  title: 'aqua.pages.netOperationLines.title',
  description: 'aqua.pages.netOperationLines.description',
  endpoint: 'NetOperationLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'netOperationId',
      label: 'aqua.fields.netOperationId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'NetOperation',
        labelKeys: ['operationNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'netOperationId', label: 'aqua.fields.netOperationId' },
    { key: 'projectCageId', label: 'aqua.fields.projectCageId' },
    { key: 'note', label: 'aqua.fields.note' },
  ],
};
